# Generated by Django 3.1.7 on 2021-04-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='сертификат')),
                ('assessment', models.TextField(max_length=50, verbose_name='оценка')),
                ('image', models.ImageField(upload_to='certifications', verbose_name='изображение')),
                ('date', models.DateField(max_length=10, verbose_name='дата получения')),
                ('url', models.URLField(default='https://', max_length=100, verbose_name='ссылка на сертификат')),
                ('is_education', models.BooleanField(default=False, verbose_name='по образованию?')),
            ],
            options={
                'verbose_name': 'сертификат',
                'verbose_name_plural': 'сертификаты',
            },
        ),
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('message', models.TextField(max_length=300, verbose_name='сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='учебное заведение')),
                ('date_for', models.DateField(max_length=10, verbose_name='дата начала учебы')),
                ('date_to', models.DateField(max_length=10, verbose_name='дата окончания обучения')),
            ],
            options={
                'verbose_name': 'мое образование',
                'verbose_name_plural': 'мое образование',
            },
        ),
        migrations.CreateModel(
            name='MyHobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='хобби/увлечения')),
                ('description', models.TextField(max_length=300, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'мои хобби и увлечения',
                'verbose_name_plural': 'мои хобби и увлечения',
            },
        ),
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('address', models.CharField(default='', max_length=100, verbose_name='адрес')),
                ('phone', models.CharField(max_length=15, verbose_name='телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
            ],
            options={
                'verbose_name': 'информация обо мне',
                'verbose_name_plural': 'информация обо мне',
            },
        ),
        migrations.CreateModel(
            name='MySkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='мой навык')),
                ('description', models.TextField(max_length=300, verbose_name='описание')),
                ('assessment', models.PositiveSmallIntegerField(default=50, verbose_name='оценка навыка')),
            ],
            options={
                'verbose_name': 'мой навык',
                'verbose_name_plural': 'мои навыки',
            },
        ),
        migrations.CreateModel(
            name='PersonalQualities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='достоинство/недостаток')),
                ('description', models.TextField(max_length=300, verbose_name='описание')),
                ('good_or_bad', models.BooleanField(default=True, verbose_name='это достоинство?')),
            ],
            options={
                'verbose_name': 'мои достоинства/недостатки',
                'verbose_name_plural': 'мои достоинства/недостатки',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя проекта')),
                ('description', models.TextField(max_length=300, verbose_name='описание')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='изображение')),
                ('url', models.URLField(default='https://', max_length=100, verbose_name='ссылка на проект')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Соцсеть')),
                ('image', models.ImageField(upload_to='social_network/', verbose_name='изображение')),
                ('url', models.URLField(default='https://', max_length=100, verbose_name='ссылка на сайт')),
            ],
            options={
                'verbose_name': 'соцсеть',
                'verbose_name_plural': 'соцсети',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=100, verbose_name='имя организации')),
                ('position', models.TextField(max_length=100, verbose_name='должность')),
                ('date_for', models.DateField(max_length=10, verbose_name='дата начала работы')),
                ('date_to', models.DateField(default='', max_length=10, verbose_name='дата окончания работы')),
            ],
            options={
                'verbose_name': 'место работы',
                'verbose_name_plural': 'место работы',
            },
        ),
    ]
