# Generated by Django 3.1.7 on 2021-04-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalqualities',
            options={'ordering': ['-good_or_bad'], 'verbose_name': 'мои достоинства/недостатки', 'verbose_name_plural': 'мои достоинства/недостатки'},
        ),
        migrations.AddField(
            model_name='myskills',
            name='icons',
            field=models.CharField(default='fa fa-check-square-o', max_length=50, verbose_name='Иконка Font Awesome'),
        ),
    ]
