# Generated by Django 3.1.7 on 2021-05-11 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210403_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='категория')),
                ('slug', models.SlugField(max_length=100, verbose_name='slug')),
            ],
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-date_to'], 'verbose_name': 'место работы', 'verbose_name_plural': 'место работы'},
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_projects', to='portfolio.projectscategory'),
        ),
    ]
