# Generated by Django 3.1.7 on 2021-05-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210511_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectscategory',
            options={'verbose_name': 'категория проекта', 'verbose_name_plural': 'категории проектов'},
        ),
        migrations.RenameField(
            model_name='myskills',
            old_name='icons',
            new_name='icon',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='image',
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='icon',
            field=models.CharField(default='fa fa-check-square-o', max_length=50, verbose_name='Иконка Font Awesome'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_projects', to='portfolio.projectscategory', verbose_name='категория проекта'),
        ),
    ]
